RECIPE = 'recipe'
USER = 'user'
ERROR = 'error'
REVIEW = 'review'
URL = 'url'
TYPE = 'type'

RECIPE_ID = 'recipe_id'
SHORT_NAME = 'short_name'
FULL_NAME = 'full_name'
AUTHOR_ID = 'author_id'
INGREDIENTS = 'ingredients'
DIRECTIONS = 'directions'
DETAIL = 'detail'
IMAGE_URL = 'image_url'
DESCRIPTION = 'description'
FACTS_TIME = 'facts_time'
FACTS_SERVES = 'facts_serves'
REVIEW_COUNT = 'review_count'
RATING = 'rating'
COMMENT = 'comment'
REVIEW_ID = 'review_id'
CATEGORY = 'category'
AUTHOR_URL = 'author_url'
USER_AVATAR_URL = 'user_avatar_url'

USERNAME = 'username'
FOLLOWER = 'follower'
FOLLOWING = 'following'
USER_ID = 'user_id'
FOLLOW = 'follow'

SCRIPT = 'script'
